DROP TABLE USERS;

CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT CONSTRAINT PK PRIMARY KEY, 
    NAME CHAR(24) NOT NULL, 
    EMAIL CHAR(36) NOT NULL, 
    PASS CHAR(70) NOT NULL, 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    PASSWORD_RESET_AT TIMESTAMP DEFAULT NULL, 
    PASSWORD_RESET BOOLEAN DEFAULT FALSE,
    EMAIL_VERIFIED BOOLEAN DEFAULT FALSE,
    CONSTRAINT UNIQUE_EMAIL UNIQUE(EMAIL));

